# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AlterField(
            model_name='page',
            name='url',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='page',
            unique_together=set([('url', 'modified')]),
        ),
    ]
