# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-05 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20160824_2143'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={},
        ),
        migrations.AlterField(
            model_name='menuentry',
            name='href',
            field=models.CharField(blank=True, max_length=255, verbose_name='Links to'),
        ),
        migrations.AlterField(
            model_name='page',
            name='url',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='page',
            unique_together=set([]),
        ),
    ]
