# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-05 12:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0002_template'),
        ('content', '0003_auto_20160905_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='layout.Template'),
        ),
    ]
