# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-15 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_auto_20160906_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogentry',
            name='status',
            field=models.CharField(choices=[('P', 'Published'), ('D', 'Draft'), ('A', 'Archived')], default='P', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='status',
            field=models.CharField(choices=[('P', 'Published'), ('D', 'Draft'), ('A', 'Archived')], default='P', max_length=1),
            preserve_default=False,
        ),
    ]
