# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-15 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_auto_20160915_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogentry',
            name='tags',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
