# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-25 02:52
from __future__ import unicode_literals

from django.db import migrations
import layout.models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_auto_20161025_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='template',
            field=layout.models.TemplateField(),
        ),
    ]
