# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-28 00:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_auto_20161025_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='extra_header_content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
