# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-22 12:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_auto_20170211_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagehistory',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='content.Page'),
        ),
    ]
