# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-04 11:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0016_auto_20170223_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogentry',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
