# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-23 00:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0016_auto_20170223_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagehistory',
            name='type',
            field=models.CharField(choices=[('D', 'Draft'), ('F', 'Future'), ('H', 'History')], default='H', max_length=1),
        ),
    ]
