# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-05 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0017_auto_20170305_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogentry',
            name='slug',
            field=models.SlugField(max_length=255, unique_for_month='created'),
        ),
    ]
