# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-20 23:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0017_pagehistory_type'),
        ('content', '0018_auto_20170305_2054'),
    ]

    operations = [
    ]
