# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-11 04:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LayoutPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
                'permissions': (('admin', 'Can change templates and stylesheets'), ('files', 'Can view files and images')),
            },
        ),
    ]
