# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-05 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0002_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='name',
            field=models.CharField(default='fruitcake', max_length=32, unique=True),
            preserve_default=False,
        ),
    ]
