# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-24 23:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_auto_20161025_1231'),
        ('layout', '0003_template_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Template',
        ),
    ]
